server/views.py
from flask import Flask, Blueprint, render_template, request
from led import *
import io
from relay import relay_o
from fan_c import fan_c
from temperature import read_temp
from pwm import cooling, heating 
from pid import pid_h, pid_c
from controller import controller_h, controller_c


main = Blueprint('main', __name__,)
control = Blueprint('control', __name__,)
project = Blueprint('project', __name__,)
parameters=Blueprint('parameters', __name__,)


@main.route('/')
def index():
	return render_template('index.html')

	
@control.route('/', methods=['POST','GET'])
def panel():
    now=round(read_temp(),2)
    
##################################
### Methods - LED + TEMP + FAN ###
##################################
    
    if request.method == 'POST' and 'kitchen' in request.form:
        color= request.form['kitchen']
        kitchen.change_color_string(color)

    if request.method == 'POST' and 'hall' in request.form:
        color= request.form['hall']
        hall.change_color_string(color)

    if request.method == 'POST' and 'living_room' in request.form:
        color= request.form['living_room']
        living_room.change_color_string(color)

    if request.method == 'POST' and 'bathroom' in request.form:
        color= request.form['bathroom']
        bathroom.change_color_string(color)

    if request.method == 'POST' and 'heating' in request.form:
        if controller_h.state == 1:
            temperature = request.form['heating']
            pid_h.setPoint(float(temperature))
 
    if request.method == 'POST' and 'cooling' in request.form:
        if controller_c.state == 1:
            temperature = request.form['cooling']
            pid_c.setPoint(float(temperature))
            
    if request.method == 'POST' and 'fan' in request.form:
        fan_c.pwm = request.form['fan']
        relay_o.set_pwm("enb",fan_c.pwm)
        fan_c.state=1
        relay_o.set_state(13,1)
        relay_o.set_state(14,0)



    color_now = [kitchen.get_color(),hall.get_color(),living_room.get_color(),bathroom.get_color()]
    state_now = [kitchen.get_state(),hall.get_state(),living_room.get_state(),bathroom.get_state()]
    relay_now=[]
    for i in range(1, 9):
        relay_now.append(relay_o.read_state(i))
    temperature_set=[None]*4
    temperature_set[0]=controller_h.get_state()
    temperature_set[1]=controller_c.get_state()       
    temperature_set[2]=pid_h.getPoint()
    temperature_set[3]=pid_c.getPoint()
    fan_date = [fan_c.state,fan_c.pwm]
    return render_template('control.html',color=color_now,state=state_now,relay=relay_now,temperature=temperature_set,now_temp=now,fan=fan_date) 


@control.route('/<room>/<action>', methods=['POST','GET'])
def led(room,action):
    now=round(read_temp(),2)
    
##################
### LED ON/OFF ###
##################

    if action == 'on':
        eval(room).turn_on()

    elif action == 'off':
        eval(room).turn_off()

    color_now = [kitchen.get_color(),hall.get_color(),living_room.get_color(),bathroom.get_color()]
    state_now = [kitchen.get_state(),hall.get_state(),living_room.get_state(),bathroom.get_state()]
    relay_now=[]
    for i in range(1, 9):
        relay_now.append(relay_o.read_state(i))
    temperature_set=[None]*4
    temperature_set[0]=controller_h.get_state()
    temperature_set[1]=controller_c.get_state()       
    temperature_set[2]=pid_h.getPoint()
    temperature_set[3]=pid_c.getPoint()
    fan_date = [fan_c.state,fan_c.pwm]
    return render_template('control.html',color=color_now,state=state_now,relay=relay_now,temperature=temperature_set,now_temp=now,fan=fan_date)

@control.route('/relay/<number>/<state>')
def relay(number,state):
    now=round(read_temp(),2)

#############
### Relay ###
#############
    
    if state == "1":
        # LED
        if number == "3":
            if kitchen.get_state() == 1:
                kitchen.turn_on()
            if living_room.get_state() ==1:
                living_room.turn_on()
            if bathroom.get_state() ==1:
                bathroom.turn_on()
            if hall.get_state() ==1:
                hall.turn_on()
        # DIMMER
        if number == "1":
            controller_h.turn_on()
            temperature_set[0]=1
            relay_o.set_state(11,1)
            relay_o.set_state(12,1) 
        relay_o.set_state(eval(number),1)
     
    if state == "0":
        if number == "1":
            controller_h.turn_off()
        relay_o.set_state(eval(number),0)

    color_now = [kitchen.get_color(),hall.get_color(),living_room.get_color(),bathroom.get_color()]
    state_now = [kitchen.get_state(),hall.get_state(),living_room.get_state(),bathroom.get_state()]
    relay_now=[]
    for i in range(1, 9):
        relay_now.append(relay_o.read_state(i))
    temperature_set=[None]*4
    temperature_set[0]=controller_h.get_state()
    temperature_set[1]=controller_c.get_state()       
    temperature_set[2]=pid_h.getPoint()
    temperature_set[3]=pid_c.getPoint()
    fan_date = [fan_c.state,fan_c.pwm]    
    return render_template('control.html',color=color_now,state=state_now, relay=relay_now,temperature=temperature_set,now_temp=now,fan=fan_date)

@control.route('/temperature/<HC>/<state>')
def temperature(HC,state):
    now=round(read_temp(),2)

##############################
### Heating/Cooling ON/OFF ###
##############################
    
    if HC == "heating":
        if state == "1":
            controller_c.turn_off()
            controller_h.turn_on() 
            relay_o.set_state(11,1)
            relay_o.set_state(12,1)
            relay_o.set_state(1,1)
        if state == "0":
            relay_o.set_state(1,0)
            controller_h.turn_off()
            
    if HC == "cooling":
        if state == "1":
            controller_h.turn_off()
            controller_c.turn_on()
            relay_o.set_state(1,0)
            relay_o.set_state(2,1)
            relay_o.set_state(11,1)
            relay_o.set_state(12,0) 
        if state == "0":
            controller_c.turn_off()
            relay_o.set_state(11,1)
            relay_o.set_state(12,1)
            
    if HC == "fan":
        if state == "1":
            fan_c.set_state(1)
            relay_o.set_pwm("enb",fan_c.pwm)
            relay_o.set_state(13,1)
            relay_o.set_state(14,0)
        if state == "0":
            fan_c.set_state(0) 
            relay_o.set_state(13,1)
            relay_o.set_state(14,1)
    
    fan_date = [fan_c.state,fan_c.pwm]
    color_now = [kitchen.get_color(),hall.get_color(),living_room.get_color(),bathroom.get_color()]
    state_now = [kitchen.get_state(),hall.get_state(),living_room.get_state(),bathroom.get_state()]
    temperature_set=[None]*4
    temperature_set[0]=controller_h.get_state()
    temperature_set[1]=controller_c.get_state()    
    temperature_set[2]=pid_h.getPoint()
    temperature_set[3]=pid_c.getPoint()
    relay_now=[]  
    for i in range(1, 9):
        relay_now.append(relay_o.read_state(i))
        
    return render_template('control.html',color=color_now,state=state_now, relay=relay_now,temperature=temperature_set,now_temp=now,fan=fan_date)



@parameters.route('/',methods=['POST','GET'])
def parametr():

###################
### PID + PWM / ###
###################
    
    
    if request.method == 'POST' and 'CK' in request.form:
        try:
            K = request.form['CK']
            pid_c.setKp(float(K))
        except:
            pass
    if request.method == 'POST' and 'CKd' in request.form:
        try:
            Kd = request.form['CKd']
            pid_c.setKd(float(Kd))
        except:
            pass
    if request.method == 'POST' and 'CKi' in request.form:
        try:
            Ki = request.form['CKi']
            pid_c.setKi(float(Ki))
        except:
            pass
    if request.method == 'POST' and 'HK' in request.form:
        try:
            K = request.form['HK']
            pid_h.setKp(float(K))
        except:
            pass
    if request.method == 'POST' and 'HKd' in request.form:
        try:
            Kd = request.form['HKd']
            pid_h.setKd(float(Kd))
        except:
            pass
    if request.method == 'POST' and 'HKi' in request.form:
        try:
            Ki = request.form['HKi']
            pid_h.setKi(float(Ki))
        except:
            pass
        
        
    if request.method == 'POST' and 'CBP' in request.form:
        try:
            x = request.form['CBP']
            cooling.changeBreakPoint(float(x))
        except:
            pass 
    if request.method == 'POST' and 'CHis' in request.form:
        try:
            x = request.form['CHis']
            cooling.changeHysteresis(float(x))
        except:
            pass
        
    if request.method == 'POST' and 'HBP' in request.form:
        try:
            x = request.form['HBP']
            heating.changeBreakPoint(float(x))
        except:
            pass
    if request.method == 'POST' and 'HHis' in request.form:
        try:
            x = request.form['HHis']
            heating.changeHysteresis(float(x))
        except:
            pass
        
    heat=[None]*5
    cool=[None]*5        
    heat[0]=round(pid_h.Kp,2)
    heat[1]=round(pid_h.Ti,2)
    heat[2]=round(pid_h.Td,2)
    heat[3]=round(heating.break_point,2)
    heat[4]=round(heating.hysteresis,2)
    cool[0]=round(pid_c.Kp,2)
    cool[1]=round(pid_c.Ti,2)
    cool[2]=round(pid_c.Td,2)
    cool[3]=round(cooling.break_point,2)
    cool[4]=round(cooling.hysteresis,2)
    return render_template('reg.html',pid_cool=cool,pid_heat=heat)





@parameters.route('/reset/<device>')
def def_value(device):
    heat=[None]*5
    cool=[None]*5
    
#####################
### Reset PID/PWM ###
#####################

    if device == "pid_h":
        pid_h.reset("cooling")
    if device == "pid_c":
        pid_c.reset("heating")
    if device == "sat_h":
        heating.reset("heating")
    if device == "sat_c":
        cooling.reset("cooling")
    

server/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
     <script src="https://code.jquery.com/jquery-3.3.1.js"></script>
    {% block head %} {% endblock %}
</head>

<body>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample08" aria-controls="navbarsExample08" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse justify-content-md-center" id="navbarsExample08">
    <ul class="navbar-nav">
      <li class="nav-item ">
        <a class="nav-link" href="{{ url_for('main.index') }}">Strona główna <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item ">
        <a class="nav-link" href="{{ url_for('control.panel') }}">Panel sterowania <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item ">
        <a class="nav-link" href="{{ url_for('parameters.parametr') }}">Parametry<span class="sr-only">(current)</span></a>
      </li>     
      
      
      
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="dropdown08" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Inne</a>
        <div class="dropdown-menu" aria-labelledby="dropdown08">
          <a class="dropdown-item " href="{{ url_for('project.lab') }}">Opis laboratorium</a>
          <a class="dropdown-item " href="{{ url_for('project.thesis') }}">Praca inżynierska</a>
        </div>
      </li>
    </ul>
  </div>
</nav>

 <div class="container">
        {% block body %} {% endblock %}
</div>

    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
</body>

</html>

server/templates/control.html
{% extends 'base.html' %}
{% block head %}
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">
        



        {{ colorpicker.loader() }}
        {{ colorpicker.picker(ids=['.kitchen', '.hall', '.living_room', '.bathroom']) }}
<title>Panel sterowania</title>
{% endblock %}

{% block body %}


<main role="main">
    <div class="jumbotron">
		<p class="display-4 d-inline">Oświetlenie</p>
		<div class="float-right">

					{% if relay[2]==1 %}
						<a  href="/control/relay/3/0" class="btn btn-lg btn-dark bigonof" role="button">Wyłącz</a> 
					{% else %}
						<a href="/control/relay/3/1" class="btn btn-lg btn-dark active bigonof" role="button">Włącz</a> 
					{% endif %}
					</div>
		<hr class="col-xs-12">
		<div class="row justify-content-center">
			<div class="col-sm-6 col-lg-3 border rounded">
				<p class="h4 d-inline">Kuchnia</p>
				<div class="float-right">
					{% if state[0]==1 %}
						<a  href="/control/kitchen/off" class="btn  btn-dark onof" role="button">Wyłącz</a> 
					{% else %}
						<a href="/control/kitchen/on" class="btn  btn-dark active onof" role="button">Włącz</a> 
					{% endif %}
				</div>
				<form method="post" action="{{url_for('control.panel') }}">
					<input class='kitchen' name='kitchen' value={{ color[0] }} />
					<input class="btn btn-primary btn-sm " name="kitchen" type="submit" value="✓">
				</form>
			</div>

			<div class="col-sm-6 col-lg-3 border rounded">
				<p class="h4 d-inline">Hol</p>
				<div class="float-right">
					{% if state[1]==1 %}
						<a href="/control/hall/off" class="btn btn-dark onof" role="button">Wyłącz</a> 
					{% else %}
						<a href="/control/hall/on" class="btn btn-dark active onof" role="button">Włącz</a> 
					{% endif %}
				</div>
				<form method="post" action="{{url_for('control.panel') }}">
					<input class='hall' name='hall' value={{ color[1] }} />
					<input class="btn btn-primary btn-sm" name="hall" type="submit" value="✓">
				</form>
			</div>
			<div class="col-sm-6 col-lg-3 border rounded">
				<p class="h4 d-inline">Salon</p>
				<div class="float-right">
					{% if state[2]==1 %}
						<a href="/control/living_room/off" class="btn btn-dark onof" role="button">Wyłącz</a> 
					{% else %}
						<a href="/control/living_room/on" class="btn btn-dark active onof" role="button">Włącz</a> 
					{% endif %}
				</div>
				<form method="post" action="{{url_for('control.panel') }}">
					<input class='living_room' name='living_room' value={{ color[2] }} />
					<input class="btn btn-primary btn-sm" name="living_room" type="submit" value="✓">
				</form>
			</div>
			<div class="col-sm-6 col-lg-3 border rounded">
				<p class="h4 d-inline">Łazienka</p>
				<div class="float-right">
					{% if state[3]==1 %}
						<a href="/control/bathroom/off" class="btn  btn-dark  onof" role="button">Wyłącz</a> 
					{% else %}
						<a href="/control/bathroom/on" class="btn  btn-dark active onof" role="button">Włącz</a> 
					{% endif %}
				</div>			
				<form method="post" action="{{url_for('control.panel') }}">
					<input class='bathroom' name='bathroom' value={{ color[3] }} />
					<input class="btn btn-primary btn-sm" name="bathroom" type="submit" value="✓">
				</form>
			</div>

		</div>	
		
		<hr class="col-xs-12">
		<p class="display-4">Przekaźniki</p>
			<hr class="col-xs-12">
		<div class="row justify-content-center">
			{% if relay[0]==1 %}
				<div class="col-sm-6 col-lg-3 border rounded bg-success">
				{% else %}
				<div class="col-sm-6 col-lg-3 border rounded bg-danger">
				{% endif %}
				<p class="h4 d-inline">Ściemniacz</p>
				<div class="float-right">
					{% if relay[0]==1 %}
						<a  href="/control/relay/1/0" class="btn btn-dark onof" role="button">Wyłącz</a> 
					{% else %}
						<a href="/control/relay/1/1" class="btn btn-dark active onof" role="button">Włącz</a> 
					{% endif %}
				</div>
			</div>
		{% if relay[1]==1 %}
				<div class="col-sm-6 col-lg-3 border rounded bg-success">
				{% else %}
				<div class="col-sm-6 col-lg-3 border rounded bg-danger">
				{% endif %}
				<p class="h4 d-inline">Wentylator</p>
				<div class="float-right">
					{% if relay[1]==1 %}
						<a  href="/control/relay/2/0" class="btn btn-dark onof" role="button">Wyłącz</a> 
					{% else %}
						<a href="/control/relay/2/1" class="btn btn-dark active onof" role="button">Włącz</a> 
					{% endif %}
				</div>

			</div>
			{% if relay[2]==1 %}
				<div class="col-sm-6 col-lg-3 border rounded bg-success">
				{% else %}
				<div class="col-sm-6 col-lg-3 border rounded bg-danger">
				{% endif %}
				<p class="h4 d-inline">LED</p>
					<div class="float-right">
					{% if relay[2]==1 %}
						<a  href="/control/relay/3/0" class="btn btn-dark onof" role="button">Wyłącz</a> 
					{% else %}
						<a href="/control/relay/3/1" class="btn btn-dark active onof" role="button">Włącz</a> 
					{% endif %}
					</div>

			</div>
			{% if relay[3]==1 %}
				<div class="col-sm-6 col-lg-3 border rounded bg-success">
				{% else %}
				<div class="col-sm-6 col-lg-3 border rounded bg-danger">
				{% endif %}
				<p class="h4 d-inline">CH4</p>
				<div class="float-right">
					{% if relay[3]==1 %}
						<a  href="/control/relay/4/0" class="btn btn-dark onof" role="button">Wyłącz</a> 
					{% else %}
						<a href="/control/relay/4/1" class="btn btn-dark active onof" role="button">Włącz</a> 
					{% endif %}
				</div>

			</div>
		</div>
		<div class="row justify-content-center">
			{% if relay[4]==1 %}
				<div class="col-sm-6 col-lg-3 border rounded bg-success">
				{% else %}
				<div class="col-sm-6 col-lg-3 border rounded bg-danger">
				{% endif %}
				<p class="h4 d-inline">CH5</p>
				<div class="float-right">
					{% if relay[4]==1 %}
						<a  href="/control/relay/5/0" class="btn btn-dark onof" role="button">Wyłącz</a> 
					{% else %}
						<a href="/control/relay/5/1" class="btn btn-dark active onof" role="button">Włącz</a> 
					{% endif %}
				</div>

			</div>
				{% if relay[5]==1 %}
				<div class="col-sm-6 col-lg-3 border rounded bg-success">
				{% else %}
				<div class="col-sm-6 col-lg-3 border rounded bg-danger">
				{% endif %}
				<p class="h4 d-inline">CH6</p>
				<div class="float-right">
					{% if relay[5]==1 %}
						<a  href="/control/relay/6/0" class="btn btn-dark onof" role="button">Wyłącz</a> 
					{% else %}
						<a href="/control/relay/6/1" class="btn btn-dark active onof" role="button">Włącz</a> 
					{% endif %}
				</div>

			</div>
				{% if relay[6]==1 %}
				<div class="col-sm-6 col-lg-3 border rounded bg-success">
				{% else %}
				<div class="col-sm-6 col-lg-3 border rounded bg-danger">
				{% endif %}
				<p class="h4 d-inline">CH7</p>
				<div class="float-right">
					{% if relay[6]==1 %}
						<a  href="/control/relay/7/0" class="btn btn-dark onof" role="button">Wyłącz</a> 
					{% else %}
						<a href="/control/relay/7/1" class="btn btn-dark active onof" role="button">Włącz</a> 
					{% endif %}
				</div>

			</div>
				{% if relay[7]==1 %}
				<div class="col-sm-6 col-lg-3 border rounded bg-success">
				{% else %}
				<div class="col-sm-6 col-lg-3 border rounded bg-danger">
				{% endif %}
				<p class="h4 d-inline">CH8</p>
				<div class="float-right">
					{% if relay[7]==1 %}
						<a  href="/control/relay/8/0" class="btn btn-dark onof" role="button">Wyłącz</a> 
					{% else %}
						<a href="/control/relay/8/1" class="btn btn-dark active onof" role="button">Włącz</a> 
					{% endif %}
				</div>

			</div>
			</div>
		<hr class="col-xs-12">
		<p class="display-4 d-inline">Temperatura</p>
				<div class="float-right">
					<p class=" h3 d-inline">{{ now_temp }}°C</p>
				</div>
		<hr class="col-xs-12">
		
		<div class="row justify-content-center">
			<div class="col-sm-12 col-lg-6 border rounded">
				
				<p class="h4 d-inline">Chłodzenie</p>
				
				<div class="float-right">
					{% if temperature[1]==1 %}
						<a href="/control/temperature/cooling/0" class="btn btn-dark onof" role="button">Wyłącz</a> 
					{% else %}
						<a href="/control/temperature/cooling/1" class="btn btn-dark active onof" role="button">Włącz</a> 
					{% endif %}
				</div>
				<div class="row">
				<p class=" h6 d-inline">Temperatura zadana = {{ temperature[3] }}</p>
				</div>
				<div class=" row justify-content-center float-center">
				<div class="form-group">
				    <form method="post" action="{{url_for('control.panel') }}">
					<input class='cooling' name='cooling' type="number" step="0.1" min="16" max="22" placeholder="°C">
					<input class="btn btn-primary btn-sm " name="cooling" type="submit" value="✓">
					</form>
				</div>
				
				</div>
			</div>

			<div class="col-sm-12 col-lg-6 border rounded">
				
				<p class="h4 d-inline">Ogrzewanie</p>
				
				<div class="float-right">
					{% if temperature[0]==1 %}
						<a href="/control/temperature/heating/0" class="btn btn-dark onof" role="button">Wyłącz</a> 
					{% else %}
						<a href="/control/temperature/heating/1" class="btn btn-dark active onof" role="button">Włącz</a> 
					{% endif %}
				</div>
				<div class="row">
				<p class=" h6 d-inline">Temperatura zadana = {{ temperature[2] }}</p>
				</div>
				<div class=" row justify-content-center float-center">
				<div class="form-group">
				    <form method="post" action="{{url_for('control.panel') }}">
					<input class="heating" name='heating' type="number" step="0.1" min="20" max="60" placeholder="°C">
					<input class="btn btn-primary btn-sm " name="heating" type="submit" value="✓">
					</form>
				</div>
				
				</div>
				</div>
			</div>
				<hr class="col-xs-12">
				
					<p class="display-4 d-inline">Wentylator </p>
				<div class="float-right">
					<p class=" h3 d-inline">{{ fan[1] }}%</p>
					{% if fan[0]==1 %}
						<a  href="/control/temperature/fan/0" class="btn btn-lg btn-dark bigonof" role="button">Wyłącz</a> 
					{% else %}
						<a href="/control/temperature/fan/1" class="btn btn-lg btn-dark active bigonof" role="button">Włącz</a> 
					{% endif %}
				</div>
				
				<hr class="col-xs-12">
					<div class="form-group">
				    <form method="post" action="{{url_for('control.panel') }}">
					<input class='form-control-range' name='fan' type="range" step="1" min="0" max="100">
					
					<div class ="float-right">
					<input class="btn btn-primary btn-sm " name="fan" type="submit" value="✓">
					</div>
					</form>
					
				</div>
				
				
	</div>
    </div>

</main>

{% endblock %}

server/templates/index.html
{% extends 'base.html' %}

{% block head %}
<title>Strona główna</title>
{% endblock %}

{% block body %}
<br>

<br>
<main role="main">
    <div class="jumbotron">
        <div class="row justify-content">
        <div class="col-sm-10 mx-auto">
<h2>Stanowisko laboratoryjne automatyki budynków</h1>
</div>
</div>
<div class="col-sm-5 mx-auto">
<img src="../static/jednostkacentralna.png" class="img-fluid" alt="Jednostka centralna">
</div>
<div class="col-sm-10 mx-auto">
<p>Stanowiska laboratoryjne automatyki budynków oparte jest o platformę Raspberry Pi wraz z interfejsem użytkownika. Projekt w założeniu ma być mobilny, stąd też decyzja o umieszczeniu go w dwóch walizkach, z czego jedna pełniąca funkcję jednostki centralnej, zaopatrzonej w mikrokomputer Raspberry Pi wraz z osprzętem oraz modelem domu podświetlanym LEDami. W drugiej natomiast ulokowano model cieplny, zawierający żarówkę halogenową oraz ogniwo Peltiera będące kolejno imitacją ogrzewania i klimatyzacji w budynku. Model dopełniają czujnik temperatury oraz wentylator. Projekt zakłada użycie regulatora do zapewnienia sterowania temperaturą obiektu.
</p>
        </div>
    </div>
</main>
{% endblock %}